### ISSUE TITLE
Forbid defining implicit conversion methods (to_ary, to_hash, to_int, to_str)

### ISSUE THREAD

**Issue by dduugg** [Shopify/rubocop-sorbet#163]
Ruby supports a few methods that allow implicit type [conversions](https://docs.ruby-lang.org/en/3.2/implicit_conversion_rdoc.html).

Since Sorbet is a nominal (not [structural](https://sorbet.org/docs/faq#can-i-use-sorbet-for-duck-typed-code)) type system, implicit conversion is currently [unsupported](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Pathname%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7B%20returns%28String%29%20%7D%0A%20%20def%20to_str%0A%20%20%20%20to_s%0A%20%20end%0Aend%0A%0A''%20%2B%20Pathname%28'%2F'%29%20%23%20%3D%3E%20%22%2F%22).

I would like to write a cop that adds violations when implicit conversion methods are defined. Would the maintainers be amenable to this?

**Comment by Morriar** [comment]
Yeah it seems like a good idea to have such a cop 👍 

Depending on the amount of violations it creates, we may not enable it by default though.
