### ISSUE TITLE
Sorbet/ForbidTStruct - autocorrect does not handle optional params without default or factory

### ISSUE THREAD

**Issue by okhwaja** [Shopify/rubocop-sorbet#179]
Hi, was experimenting with the new ForbidTStruct cop and noticed the autocorrect does not correctly generate the initializer for nilable properties without an explicitly defined default/factory value. The initializer should have them as optional arguments

Example
```
class Foo < T::Struct
  const :name, T.nilable(String)
end

Foo.new.name # <--- nil
```

Expected after autocorrect
```
class Foo
  extend T::Sig

  sig { returns(T.nilable(String)) }
  attr_reader :name

  sig { params(name: T.nilable(String)).void }
  def initialize(name: nil)
    @name = name
  end
end

Foo.new.name # <--- nil
```

Current output of autocorrect
```
class Foo
  extend T::Sig

  sig { returns(T.nilable(String)) }
  attr_reader :name

  sig { params(name: T.nilable(String)).void }
  def initialize(name:)
    @name = name
  end
end

Foo.new.name # <--- ArgumentError missing keyword: :name
```

The result is that `name` becomes a required param

**Comment by Morriar** [comment]
Good catch. I tried a fix here: https://github.com/Shopify/rubocop-sorbet/pull/180
