### ISSUE TITLE
Suggestion: Cop for missing `require "sorbet-runtime"`

### ISSUE THREAD

**Issue by JamieMagee** [Shopify/rubocop-sorbet#197]
This would be something like `Sorbet/EnforceRuntimeChecks` and would ensure static _and_ runtime checks are enabled.

**Comment by andyw8** [comment]
🤔 How would we determine which file to check?

**Comment by JamieMagee** [comment]
Anything with a valid sigil? Here's a grep command that I've been using to achieve the same thing

```
grep --files-without-match "require \"sorbet-runtime\"" $(grep --files-with-matches "# typed: " --include "*.rb" --recursive)
```

**Comment by andyw8** [comment]
But it doesn't need to be added in every file. In a gem you'd typically have it in the gem's entry point file:

https://github.com/Shopify/tapioca/blob/01d7796c7d1d819fc3f03ef655e0cdef1aa6c44e/lib/tapioca.rb#L4

and in a Rails app you'd usually have it in `boot.rb`.

**Comment by andyw8** [comment]
Yes, e.g. with `# typed: false`.

I agree the Sorbet docs could be better for this.

**Comment by andyw8** [comment]
Closing since there doesn't seem to be a valid case for this.
