### ISSUE TITLE
Discourage misuses of `T::Enum`

### ISSUE THREAD

**Issue by egiurleo** [Shopify/rubocop-sorbet#219]
While `T::Enum` provides a low-effort, type-safe way to construct an exhaustive set of values, it is also less performant than implementing the same functionality using data structures from Ruby (e.g. list of constants).

rubocop-sorbet should discourage using `T::Enum` in ways that exacerbates performance issues or doesn't use `T::Enum` for its intended purpose.

Potential cops include:
- [x] Convert any `T::Enum` with one value into a constant
- [x] Disallow including the `Comparable` module in `T::Enum` (comparing `T::Enum` values has particularly poor performance)
- [ ] ~~Disallow case statements with more than a certain number of `T::Enum` values ([motivation](https://github.com/sorbet/sorbet/issues/7532))~~

---

EDIT (2024-04-22): I decided not to create a cop forbidding case statements above a certain size.

After running some benchmarks, it seems that, at runtime, case statements have exponentially decreasing performance whether they're being used with `T::Enum` values or Ruby constants, and when statically type checking, time spent increases linearly. There isn't an obvious point at which performance drops off in either of these cases, making any cut off we assign totally arbitrary. We can revisit this issue if it comes up in the future.

<img width="972" alt="Screenshot 2024-04-22 at 4 25 43 PM" src="https://github.com/Shopify/rubocop-sorbet/assets/9601737/724a915f-c7ff-457e-9455-0badf297224d">

<img width="841" alt="Screenshot 2024-04-22 at 4 28 00 PM" src="https://github.com/Shopify/rubocop-sorbet/assets/9601737/af26ee48-8559-4e40-b717-be3f1e1866ca">

**Comment by egiurleo** [comment]
@amomchilov That's really interesting! I will take a look at this as it ties in well with our Sorbet performance project. I wonder if we could apply the same logic to the `<=>` method? I did some benchmarks where `<`/`>` comparisons were 8x slower with `T::Enum` values than constants, which was pretty wild to me.

**Comment by amomchilov** [comment]
@egiurleo `Comparable` in general isn't _great_ for performance, because it does a bunch of branching, error handling, etc. E.g.

* if you return a number greater than `1` or less than `-1`
* if you return `nil`, it'll raise an error
* etc.

It might be worth manually deriving all the `<`/`<=`/`==`/`!=`/`>=`/`>` operators. See [this example](https://github.com/Shopify/shop-server/pull/65585/files#diff-23ff2f9142f177087a0b09550bf3e090ceaa66a405549029d9e3fbc6467390b2R56-R74) for comparison.
