### ISSUE TITLE
New deprecation warning after upgrading rubocop to 1.65

### ISSUE THREAD

**Issue by mikdiet** [Shopify/rubocop-sorbet#238]
I'm getting this warning after rubocop updated to the latest.

```
/usr/local/bundle/gems/rubocop-sorbet-0.8.3/lib/rubocop/cop/sorbet/sigils/valid_sigil.rb:21: warning: `Cop.registry` is deprecated. Use `Registry.global` instead.
```

**Comment by andyw8** [comment]
Thanks. I see this was introduced by https://github.com/rubocop/rubocop/pull/13032

**Comment by MikeMcQuaid** [comment]
@andyw8 Any chance of a new release with the fix for this in it? The warning is hard to bypass and pretty annoying. Thanks for all your work on this useful cop ❤️

**Comment by andyw8** [comment]
@MikeMcQuaid released: https://rubygems.org/gems/rubocop-sorbet/versions/0.8.4
