### ISSUE TITLE
Infinite loop using autocorrection

### ISSUE THREAD

**Issue by dduugg** [Shopify/rubocop-sorbet#25]
I've attempted to introduce `rubocop-sorbet` in a couple projects, and consistently encounter infinite loops with autocorrection. A fairly minimal repro is:
```
bundle gem foo
cd foo

# make gemspec valid:
sed -ie 's/TODO: //g' foo.gemspec
sed -i '' '/uri/d' foo.gemspec
sed -i '' '/homepage/d' foo.gemspec

bundle add rubocop rubocop-sorbet
cat << EOF >> .rubocop.yml
---
require:
  - rubocop-sorbet
EOF
bundle exec rubocop -a
```

the last fails, with the relevant part of the output looking like this:
```
Infinite loop detected in /Users/dug/git/foo/Gemfile.
/Users/dug/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rubocop-0.80.1/lib/rubocop/runner.rb:273:in `block in iterate_until_no_changes'
/Users/dug/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rubocop-0.80.1/lib/rubocop/runner.rb:269:in `loop'
/Users/dug/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rubocop-0.80.1/lib/rubocop/runner.rb:269:in `iterate_until_no_changes'
/Users/dug/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rubocop-0.80.1/lib/rubocop/runner.rb:240:in `do_inspection_loop'
/Users/dug/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rubocop-0.80.1/lib/rubocop/runner.rb:119:in `block in file_offenses'
```

`Gemfile` ends up with 100 `# frozen_string_literal: true` lines, and also each typed sigil, e.g.:
```
# frozen_string_literal: true
# typed: strong
# typed: strict
# typed: true
# typed: false
# typed: ignore
# typed: false
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# (97 more of the previous line)
```
I typically configure `rubocop.yml` differently, e.g. disabling strong & strict sigils, but still see infinite loops.
Also, this isn't specific to `Gemfile` – even if that file is excluded, it repros on subsequent files.

**Comment by paracycle** [comment]
Hi @dduugg, apologies for the super late response on this. It seems no one on the team was notified by this issue.

We've just released v0.4.0 of the gem that should fix this problem. It ships with a saner default configuration that just enables `FalseSigil` and not the other ones.

I did test this again using your repro script (which was very helpful by the way ❤️) and can see that autocorrect is just marking files as `# typed: false` only (and does not touch `Gemfile` at all).

Could you please test this and let us know if the problem persists? Thanks.
