### ISSUE TITLE
Error In Sorbet/ParametersOrderingInSignature when parameter name is missing

### ISSUE THREAD

**Issue by riley-klingler** [Shopify/rubocop-sorbet#28]
If you forget to include the parameter name in a signature, `Sorbet/ParametersOrderingInSignature` fails rather than reporting an error.

## Repro:
```
# typed: true

class Test
  extend T::Sig

  sig { params(Integer).void }
  def test(abc); end
end
```

## Actual Behavior:
```
flexport$ rubocop -a test.rb
Inspecting 1 file
An error occurred while Sorbet/ParametersOrderingInSignature cop was inspecting /Users/rklingler/flexport/test.rb:7:2.
To see the complete backtrace run rubocop -d.
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Sorbet/ParametersOrderingInSignature cop was inspecting /Users/rklingler/flexport/test.rb:7:2.
```

## Expected Behavior:
I would expect the cop to not crash. Since the problem isn't exactly about parameter ordering, it may not be this cop's responsibility to report the error, but it shouldn't crash.

### Version Info
Rubocop: 0.80.1
Rubocop-sorbet: 0.3.7

**Comment by paracycle** [comment]
Thanks for reporting this, we just fixed it. I will make a release before the end of the week and the fix will be included there.

**Comment by riley-klingler** [comment]
Awesome, thanks!
