### ISSUE TITLE
Improve autocorrection for `Sorbet/ForbidIncludeConstLiteral` cop

### ISSUE THREAD

**Issue by paracycle** [Shopify/rubocop-sorbet#53]
Changing the autocorrect of:
```ruby
class Foo
  include Bar.module
end
```
from:
```ruby
class Foo
  BarInclude = Bar.module
  include BarInclude
end
```
to:
```ruby
class Foo
  T.unsafe(self).include Bar.module
end
```
is better since that allows Sorbet to totally ignore the `include` call but the runtime behaviour is exactly the same and we don't end up creating new constant names.

If users still need the methods from that include, they can add a shim RBI file to signal the inclusion of the proper module kind.

**Comment by Morriar** [comment]
Should be fixed in https://github.com/Shopify/rubocop-sorbet/pull/85.
