### ISSUE TITLE
HasSigil SuggestedStrictness Not Supported?

### ISSUE THREAD

**Issue by bmulholland** [Shopify/rubocop-sorbet#64]
I'm trying to enable suggested strictness for sigils, but getting a warning that it isn't supported?

I'm referencing https://github.com/Shopify/rubocop-sorbet/blob/master/manual/cops_sorbet.md#sorbethassigil

rubocop-sorbet 0.6.1

.rubocop.yml
```
Sorbet/HasSigil:
  Enabled: true
  SuggestedStrictness: true
```

Output from rubocop -a:
```
Warning: Sorbet/HasSigil does not support SuggestedStrictness parameter.

Supported parameters are:

  - Enabled
```

**Comment by Morriar** [comment]
👋 @bmulholland,

I pushed https://github.com/Shopify/rubocop-sorbet/pull/65 to fix the warnings and the options behaviour.

Until it's merged, if you want the autocorrect to work properly you should change your config to use a string:

```diff
-  SuggestedStrictness: true
+  SuggestedStrictness: "true"
```

Thanks for the bug report!

**Comment by bmulholland** [comment]
Amazing - thanks for fixing :)
