### ISSUE TITLE
ForbidRBIOutsideOfSorbetDir conflicts with sorbet docs, lacks guidance

### ISSUE THREAD

**Issue by dduugg** [Shopify/rubocop-sorbet#79]
The sorbet [docs](https://sorbet.org/docs/rbi#rbis-within-gems) advise gems to "include their external interfaces RBI files in an `rbi/` directory". This leads to `ForbidRBIOutsideOfSorbetDir` violations. (The cop would also benefit from providing guidance on structuring `sorbet/` with custom `rbi` files.)

**Comment by dduugg** [comment]
Hi @Morriar thanks for the response. Based on my reading of the sorbet docs, I think that the error message would still be off with that configuration:

> RBI files are only accepted in the sorbet/rbi/ directory.

It also doesn't provide useful guidance as to how one should structure `sorbet/rbi/` with custom rbi files (I think this is the more salient issue, FWIW).

**Comment by RyanBrushett** [comment]
With the addition of an `AllowedPaths` option for (what was) the ForbidRBIOutsideOfSorbetDir cop, the user can configure where they expect their RBI files to live, defaulting to `sorbet/rbi/**`. See #83 and [check out the doc entry for the `ForbidRBIOutsideOfAllowedPaths` cop here](https://github.com/Shopify/rubocop-sorbet/blob/master/manual/cops_sorbet.md#sorbetforbidrbioutsideofallowedpaths).

In terms of useful guidance: Opinions on structure should come from the Sorbet documentation or the tool used to generate RBI, (e.g. [Tapioca](https://github.com/shopify/tapioca)). It's up to the cop to be flexible enough to work with whatever you've settled on.

Thanks for reporting this 👍
