### ISSUE TITLE
Typo in configuration

### ISSUE THREAD

**Issue by rc-jstad** [Shopify/rubocop-sorbet#95]
This impacts 0.6.5 and 0.6.6 AFAIK

https://github.com/Shopify/rubocop-sorbet/blob/9b57082bdc60ce4237c0dd7823a924154fc335e6/config/default.yml#L42

I think this should be `Sorbet/EnforceSingleSigil`.

**Comment by Morriar** [comment]
Thanks for catching this. I just released a [new version](https://rubygems.org/gems/rubocop-sorbet/versions/0.6.7) with the fix 👍
