### ISSUE TITLE
disabling signature cops on typed: false files

### ISSUE THREAD

**Issue by ashkulz** [Shopify/rubocop-sorbet#99]
We use `Sorbet/EnforceSignatures` along with Pronto to ensure that newly added methods are having signatures. However, it doesn't make sense to add them on `typed: false` files as they won't be validated anyway. Can an option be added to not do so? e.g.
```
Sorbet/EnforceSignatures:
  Enabled: true
  EnforcedStyle: ignore_typed_false
```

**Comment by Morriar** [comment]
> However, it doesn't make sense to add them on `typed: false` files as they won't be validated anyway.

This is actually incorrect, consider the following files:

```rb
# file false.rb
# typed: false

extend T::Sig

sig { params(x: Integer).void }
def foo(x); end
```

```rb
# file true.rb
# typed: true

foo("1")
```

If you run Sorbet on those files, you'll notice that the calls from `true.rb` are actually checked against the signatures from `false.rb`:

```
true.rb:3: Expected `Integer` but found `String("1")` for argument `x` https://srb.help/7002
     3 |foo("1")
            ^^^
  Expected `Integer` for argument `x` of method `Object#foo`:
    false.rb:5:
     5 |sig { params(x: Integer).void }
                     ^
  Got `String("1")` originating from:
    true.rb:3:
     3 |foo("1")
            ^^^
Errors: 1
```

Can an option be added to not do so? e.g.
> 
> ```
> Sorbet/EnforceSignatures:
>   Enabled: true
>   EnforcedStyle: ignore_typed_false
> ```

This is a good idea! Do you want to take a shot at it? You can take a look at how we read the configuration of the cop in https://github.com/Shopify/rubocop-sorbet/blob/main/lib/rubocop/cop/sorbet/rbi/forbid_rbi_outside_of_allowed_paths.rb#L58 for example.

**Comment by Morriar** [comment]
Closing this. Please feel free to open a separate issue (or even better a pull-request) to add an option to the cop.
